### ISSUE TITLE
Cann't create a dataset for specific workspace

### ISSUE THREAD

**Issue by armen-danielyan** [haritzmedina/node-powerbi#1]
I found a solution for it.

`class PowerBI {
  constructor(accessToken, refreshToken) {
    this.baseURI = 'https://api.powerbi.com/v1.0/myorg/groups/{group_id}/';
    this.accessToken = accessToken;
    this.refreshToken = refreshToken;
  }
...
}`

You can just add group_id as a parameter for constructor.

**Comment by haritzmedina** [comment]
Thank you @armdaniel  for your comments. I'm not able to check if the fix for this issue works cause I haven't a pro version of PowerBI. But I have updated the library with your comments. If there is any problem with it, feel free to reopen the issue and I will check it.
